workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17

    scripts:
      - name: Instalar dependências
        script: |
          flutter pub get

      - name: Compilar app em modo release
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/**/*.aab
      - build/app/outputs/flutter-apk/**/*.apk
